### PR TITLE
Fixed Bug

### LINKED ISSUE #4: UI. Initial design of event page
Implement initial design for event page using User Story as guide.

Provision should be made for key features outlined for Event page.

### PR DESCRIPTION
**Pull request by vector-ok**
Fixes #4 

## How Has This Been Tested?
Please describe in detail how you tested your changes.
Include details of your testing environment, and the tests you ran to see how your change affects other areas of the code etc.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Douglasokolaa** [comment]
Hi vector Menu does not automatically close on mobile version after switching page

**Comment by vector-ok** [comment]
> Hi vector Menu does not automatically close on mobile version after switching page

Yeah. Menu has to be manually closed by tapping the menu's button again. It's the standards now.

**Comment by Douglasokolaa** [comment]
> > Hi vector Menu does not automatically close on mobile version after switching page
> 
> Yeah. Menu has to be manually closed by tapping the menu's button again. It's the standards now.

don't you think it won't be user friendly since most content will still be covered? :)

**Review by Douglasokolaa — APPROVED** [review]

**Comment by vector-ok** [comment]
> > > Hi vector Menu does not automatically close on mobile version after switching page
> > 
> > 
> > Yeah. Menu has to be manually closed by tapping the menu's button again. It's the standards now.
> 
> don't you think it won't be user friendly since most content will still be covered? :)
Ok. lets see.

**Review by ekrresa — APPROVED** [review]

**Pull request merged**
